name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    - name: Run application
      run: |
        make run &
        sleep 30  # Increase sleep duration to 30 seconds
    - name: Check server
      run: |
        curl --fail http://localhost:3000 || exit 1
